fixed modify document functions in WOQL
terminusdb/terminusdb-client-js pull request #111
Opened 2022-01-30 06:53 UTC by Neelterminusdb

2022-03-08 15:40 UTC, spl commented
https://github.com/terminusdb/terminusdb/pull/1013 has been merged, so I believe this can be restarted.

2022-03-10 09:16 UTC, spl requested changes
There are merge conflicts with `main`, and I see things like inconsistent `;` usage, so I'm wondering if this passes the lint check. I think you should merge in `main` and check.

2022-03-10 09:56 UTC, rrooij commented on lib/woqlClient.js
> +    console.log(apiUrl)
We should probably remove this

2022-03-10 11:21 UTC, spl requested changes

2022-03-10 11:21 UTC, spl commented on lib/woql.js
> + * WOQL.insert_document(WOQL.doc({ "@type" : "Person", "label": "John" }))
Indent

2022-03-10 11:21 UTC, spl commented on lib/woql.js
> + * Creates a Document which can be used in WOQL within a query
```suggestion
 * Produces an encoded form of a document that can be used by a WOQL operation such as `WOQL.insert_document`.
```

2022-03-10 11:21 UTC, spl commented on lib/woql.js
> + * @param  {object} object The document which needs to be created
```suggestion
 * @param  {object} object - Document to encode
```

2022-03-10 11:21 UTC, spl commented on lib/woql.js
> + * @returns {object} a object with encoded document
```suggestion
 * @returns {object} The encoded document
```

2022-03-10 11:46 UTC, spl approved these changes

2022-03-10 11:46 UTC, merged