converted string variables to woql variables Var
terminusdb/terminusdb-client-js pull request #141
Opened 2022-03-16 13:00 UTC by Neelterminusdb

closes https://github.com/terminusdb/terminusdb-docs/issues/111

Signed-off-by: NeelParihar <neel@terminusdb.com>

2022-03-17 10:02 UTC, spl requested changes
Just some minor changes needed. I realized I left my comments on the `.md` when they should've been on the `.js`, so just keep that in mind.

2022-03-17 14:53 UTC, Neelterminusdb commented on docs/api/woql.js.md
>  WOQL.concat(["first_name", " ", "last_name"], "full_name")
Yup forgot about that, will change it

2022-03-21 11:18 UTC, spl requested changes
In addition to these, it looks like the previous issues I mentioned have not been resolved: indentation, semicolons, and `"full_value"`.

2022-03-21 13:02 UTC, spl commented on docs/api/woql.js.md
>  WOQL.concat(["first_name", " ", "last_name"], "full_name")
The `concat` seems to be duplicated here:

```
concat([first_name, " ", last_name], full_name)
WOQL.concat(["first_name", " ", "last_name"], "full_name")
```

2022-03-22 07:08 UTC, spl approved these changes

2022-03-22 07:08 UTC, merged