fixed bug in WOQL.doc not encoding lists
terminusdb/terminusdb-client-js pull request #191
Opened 2022-05-16 11:53 UTC by Neelterminusdb

closes #190 

Signed-off-by: NeelParihar <neel@terminusdb.com>

2022-05-16 12:19 UTC, spl requested changes

2022-05-16 12:28 UTC, Neelterminusdb commented on lib/query/woqlDoc.js
> +    const list = HandleSingleArrayElement.ArrayFunction(obj);
Why didn't i think of it like that 😮  Thank you @spl 😅

2022-05-16 12:37 UTC, spl approved these changes

2022-05-16 12:38 UTC, merged

2022-05-17 20:27 UTC, wcoolidge commented
Thank you for solving this so quickly! 
I have validated that commit 57c3048 solves my issue :)